### PR TITLE
Add proper status and URL keys and handle NPE on connection failures

### PR DESCRIPTION
**Pull request by llinder**

### CODE REVIEW

**Comment by jeff-blaisdell** [comment]
👍 

Mind cherry-picking and making a PR against our upstream `hyleung`?
https://github.com/hyleung/ratpack-zipkin

**Comment by llinder** [comment]
Sure I can do that.  Not sure if we are trying to contribute back since we have these other branches.

Is the thought to merge this and release a new version but still cherrypick this and make a PR against upstream?

**Comment by jeff-blaisdell** [comment]
> Is the thought to merge this and release a new version but still cherrypick this and make a PR against upstream?

Yeah, that's what we've been doing.  So far all of our PRs have been accepted in the upstream.  We hadn't had too many changes until this past week where I think we've had ~4 PRs.  After we get yours in I'm going to try and merge back all the upstream changes into this branch.

**Comment by llinder** [comment]
changes have been merged upstream

**Pull request closed without merging**
